services:
  meshop.api:
    image: ${DOCKER_REGISTRY-}meshopapi
    container_name: meShop.Api
    build:
      context: .
      dockerfile: Sample1/src/API/meShop.API/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081 
    depends_on:
      - meshop.database
      - meshop.seq
      - meshop.identity
  
  meshop.database:
    image: postgres:latest
    container_name: meShop.Database
    environment:
      - POSTGRES_DB=meShopDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  meshop.seq:
    image: datalust/seq:latest
    container_name: meShop.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  meshop.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: meShop.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080