services:
  meshop.api:
    image: ${DOCKER_REGISTRY-}meshopapi
    container_name: meShop.Api
    build:
      context: .
      dockerfile: Sample1/src/API/meShop.API/Dockerfile
    ports:
      - 8080:8080      
  
  meshop.database:
    image: postgres:latest
    container_name: meShop.Database
    environment:
      - POSTGRES_DB=meShopDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  meshop.seq:
    image: datalust/seq:latest
    container_name: meShop.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80